#!/bin/bash

touchpadStatus=$(xinput list-props 11|grep "Tapping Enabled ("|awk '{print $5}')

if ! [ x"$1" = x ]; then 
	if [ $checkLock == "on" ]; then
  		xinput set-prop 11 285 0
  		checkLock="off"


	elif [[ "$checkLock" == "on" ]]; then
  		xinput set-prop 11 285 1
  		checkLock="on"
	fi
fi

if [[ "${touchpadStatus}" == 1 ]]; then
    checkLock="on"
    exit 0
else 
    checkLock="off"
    exit 1
fi
